In [2]:
import pandas as pd

In [3]:
data = pd.read_excel("statewise_sugarcane.xlsx")

In [4]:
data

,ANDHRAPRADESH,GUJARAT,KARNATAKA,MADHYAPRADESH,MAHARASTRA,ORISSA,TAMILNADU
0,69.60,89.60,77.00,35.30,86.50,72.40,100.80
1,74.50,85.20,84.50,35.60,79.80,64.60,104.60
2,71.10,85.50,86.00,34.00,76.40,47.10,107.00
3,76.70,79.70,88.50,20.40,81.10,58.30,104.20
4,76.70,69.70,95.90,36.90,85.50,59.00,111.20
5,71.00,65.00,79.60,40.00,80.40,58.40,101.00
6,75.40,68.80,82.90,39.10,81.00,56.70,99.80
7,72.60,71.70,91.50,38.60,83.00,61.20,106.70
8,77.20,69.10,102.60,40.00,89.00,65.90,110.30
9,80.10,69.90,100.70,42.60,90.10,52.40,108.40
10,81.40,71.40,102.90,22.20,83.30,57.40,105.30
11,82.90,70.90,81.10,38.80,78.10,63.60,101.60
12,65.80,69.40,84.40,39.50,61.80,53.00,106.80
13,72.00,72.00,65.80,43.30,57.90,59.20,91.90
14,75.00,74.00,80.20,40.90,63.20,55.80,100.80
15,76.80,74.00,83.40,43.70,77.60,65.80,104.70
16,82.20,73.00,87.90,43.60,74.90,63.40,105.10
17,82.20,72.00,85.80,42.30,80.90,55.40,107.50
18,78.50,70.20,83.00,42.20,79.00,59.80,106.20
19,74.10,80.50,90.30,40.80,84.90,61.30,101.50
20,77.90,72.40,93.80,41.00,84.90,69.50,108.40
21,81.80,63.10,90.30,35.10,84.90,59.00,111.50
22,79.40,72.10,84.10,51.40,74.60,63.50,97.70
23,78.50,72.10,90.30,55.41,82.10,66.90,103.70
24,71.80,68.90,91.20,58.95,82.20,72.30,106.80
25,76.70,70.80,84.10,48.59,74.70,64.10,101.20
26,76.00,70.70,69.00,NaN,82.60,68.80,87.10
27,80.28,66.22,80.75,NaN,92.17,64.95,92.02
28,79.33,71.97,83.00,NaN,79.50,63.06,98.24
29,76.14,60.00,90.00,NaN,74.65,59.92,100.00

In [5]:
data['MADHYAPRADESH']= data['MADHYAPRADESH'].fillna(data['MADHYAPRADESH'].mean())

In [6]:
data

,ANDHRAPRADESH,GUJARAT,KARNATAKA,MADHYAPRADESH,MAHARASTRA,ORISSA,TAMILNADU
0,69.60,89.60,77.00,35.300000,86.50,72.40,100.80
1,74.50,85.20,84.50,35.600000,79.80,64.60,104.60
2,71.10,85.50,86.00,34.000000,76.40,47.10,107.00
3,76.70,79.70,88.50,20.400000,81.10,58.30,104.20
4,76.70,69.70,95.90,36.900000,85.50,59.00,111.20
5,71.00,65.00,79.60,40.000000,80.40,58.40,101.00
6,75.40,68.80,82.90,39.100000,81.00,56.70,99.80
7,72.60,71.70,91.50,38.600000,83.00,61.20,106.70
8,77.20,69.10,102.60,40.000000,89.00,65.90,110.30
9,80.10,69.90,100.70,42.600000,90.10,52.40,108.40
10,81.40,71.40,102.90,22.200000,83.30,57.40,105.30
11,82.90,70.90,81.10,38.800000,78.10,63.60,101.60
12,65.80,69.40,84.40,39.500000,61.80,53.00,106.80
13,72.00,72.00,65.80,43.300000,57.90,59.20,91.90
14,75.00,74.00,80.20,40.900000,63.20,55.80,100.80
15,76.80,74.00,83.40,43.700000,77.60,65.80,104.70
16,82.20,73.00,87.90,43.600000,74.90,63.40,105.10
17,82.20,72.00,85.80,42.300000,80.90,55.40,107.50
18,78.50,70.20,83.00,42.200000,79.00,59.80,106.20
19,74.10,80.50,90.30,40.800000,84.90,61.30,101.50
20,77.90,72.40,93.80,41.000000,84.90,69.50,108.40
21,81.80,63.10,90.30,35.100000,84.90,59.00,111.50
22,79.40,72.10,84.10,51.400000,74.60,63.50,97.70
23,78.50,72.10,90.30,55.410000,82.10,66.90,103.70
24,71.80,68.90,91.20,58.950000,82.20,72.30,106.80
25,76.70,70.80,84.10,48.590000,74.70,64.10,101.20
26,76.00,70.70,69.00,40.394231,82.60,68.80,87.10
27,80.28,66.22,80.75,40.394231,92.17,64.95,92.02
28,79.33,71.97,83.00,40.394231,79.50,63.06,98.24
29,76.14,60.00,90.00,40.394231,74.65,59.92,100.00

In [7]:
from scipy.stats import kruskal

In [8]:
stat, p = kruskal(data["ANDHRAPRADESH"],data["GUJARAT"],data["KARNATAKA"],data["MADHYAPRADESH"],data["MAHARASTRA"],data["ORISSA"],data["TAMILNADU"])

In [9]:
print('Statistics=%.3f, p=%.3f' % (stat, p))

Statistics=177.179, p=0.000

In [10]:
alpha = 0.05
if p > alpha:
	print('Same distributions (fail to reject H0)')
else:
	print('Different distributions (reject H0)')

Different distributions (reject H0)